<!--
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { getUsageSummary, getPlans, type UsageSummary, type Plan, type UsageMetric } from '@/services/usage'
import { extractApiError } from '@/utils/apiError'

const loading = ref(true)
const error = ref('')
const summary = ref<UsageSummary | null>(null)
const plans = ref<Plan[]>([])

// Display order and copy live here rather than coming from the API: the backend
// names metrics for code, not for people, and "ai_messages" is not a label.
const METRICS: { key: UsageMetric; label: string; hint: string; resets: boolean }[] = [
  { key: 'conversations', label: 'Conversations', hint: 'Chats started across every channel', resets: true },
  { key: 'ai_messages', label: 'AI replies', hint: 'Answers generated by your agents', resets: true },
  { key: 'agents', label: 'AI agents', hint: 'Agents currently configured', resets: false },
  { key: 'seats', label: 'Team members', hint: 'People with access to this workspace', resets: false },
  { key: 'knowledge_docs', label: 'Knowledge sources', hint: 'Documents, pages and text you have added', resets: false },
]

const load = async () => {
  loading.value = true
  error.value = ''
  try {
    const [s, p] = await Promise.all([getUsageSummary(), getPlans()])
    summary.value = s
    plans.value = p
  } catch (e) {
    error.value = extractApiError(e, 'Could not load usage')
  } finally {
    loading.value = false
  }
}

onMounted(load)

const currentPlan = computed(() => summary.value?.plan ?? null)

/** 'YYYY-MM' rendered as a month a person recognises. */
const periodLabel = computed(() => {
  const period = summary.value?.period
  if (!period) return ''
  const [year, month] = period.split('-').map(Number)
  return new Date(Date.UTC(year, month - 1, 1)).toLocaleDateString(undefined, {
    month: 'long', year: 'numeric', timeZone: 'UTC',
  })
})

/** Days until the flow metrics reset, so "resets monthly" has a real number. */
const daysUntilReset = computed(() => {
  const now = new Date()
  const nextMonth = Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)
  return Math.ceil((nextMonth - now.getTime()) / 86_400_000)
})

const formatNumber = (n: number) => n.toLocaleString()

const price = (plan: Plan) =>
  plan.price_cents === 0
    ? 'Free'
    : `${(plan.price_cents / 100).toLocaleString(undefined, {
        style: 'currency', currency: plan.currency, maximumFractionDigits: 0,
      })}`

/**
 * Severity drives colour, and the thresholds are deliberate: a bar that only
 * turns red on 100% gives no warning, and one that warns at 50% is ignored.
 */
const severity = (percent: number | null, exceeded: boolean) => {
  if (exceeded) return 'over'
  if (percent === null) return 'ok'
  if (percent >= 90) return 'critical'
  if (percent >= 75) return 'warn'
  return 'ok'
}

const limitLabel = (m: { used: number; limit: number | null }) =>
  m.limit === null ? 'Unlimited' : `of ${formatNumber(m.limit)}`
</script>

<template>
  <div class="usage-page">
    <header class="page-head">
      <div>
        <h1>Usage &amp; plan</h1>
        <p class="page-sub" v-if="summary">
          {{ periodLabel }} · monthly limits reset in {{ daysUntilReset }}
          {{ daysUntilReset === 1 ? 'day' : 'days' }}
        </p>
      </div>
      <button class="btn btn-secondary" @click="load" :disabled="loading">Refresh</button>
    </header>

    <div v-if="error" class="alert-error" role="alert">{{ error }}</div>

    <div v-if="loading" class="skeleton-grid" aria-hidden="true">
      <div v-for="n in 5" :key="n" class="skeleton-row"></div>
    </div>

    <template v-else-if="summary">
      <!-- Current plan -->
      <section class="card card-full plan-summary" v-if="currentPlan">
        <div class="plan-id">
          <span class="plan-eyebrow">Current plan</span>
          <h2>{{ currentPlan.name }}</h2>
          <p v-if="currentPlan.description">{{ currentPlan.description }}</p>
        </div>
        <div class="plan-price">
          <span class="amount">{{ price(currentPlan) }}</span>
          <span v-if="currentPlan.price_cents > 0" class="per">per month</span>
        </div>
      </section>

      <!-- Meters -->
      <section class="card card-full">
        <h2 class="section-heading">This month</h2>
        <ul class="meters">
          <li v-for="m in METRICS" :key="m.key" class="meter">
            <div class="meter-head">
              <div class="meter-label">
                <span class="name">{{ m.label }}</span>
                <span class="hint">{{ m.hint }}</span>
              </div>
              <div class="meter-value" :class="severity(summary.metrics[m.key].percent, summary.metrics[m.key].exceeded)">
                <strong>{{ formatNumber(summary.metrics[m.key].used) }}</strong>
                <span class="limit">{{ limitLabel(summary.metrics[m.key]) }}</span>
              </div>
            </div>

            <!-- No track where there is no ceiling: an empty bar next to
                 "Unlimited" reads as zero progress toward something. -->
            <div v-if="summary.metrics[m.key].limit !== null" class="track">
              <div
                class="fill"
                :class="severity(summary.metrics[m.key].percent, summary.metrics[m.key].exceeded)"
                :style="{ width: `${Math.min(100, summary.metrics[m.key].percent ?? 0)}%` }"
              ></div>
            </div>

            <p v-if="summary.metrics[m.key].exceeded" class="meter-note over">
              <template v-if="m.resets">
                Limit reached. New activity still works, but upgrading lifts the cap.
              </template>
              <template v-else>
                Limit reached — you'll need to upgrade or remove one to add another.
              </template>
            </p>
          </li>
        </ul>
      </section>

      <!-- Catalog -->
      <section class="card card-full">
        <h2 class="section-heading">Plans</h2>
        <div class="plan-grid">
          <article
            v-for="p in plans"
            :key="p.code"
            class="plan-card"
            :class="{ current: p.code === currentPlan?.code }"
          >
            <div class="plan-card-head">
              <h3>{{ p.name }}</h3>
              <span v-if="p.code === currentPlan?.code" class="chip">Current</span>
            </div>
            <div class="plan-card-price">
              <span class="amount">{{ price(p) }}</span>
              <span v-if="p.price_cents > 0" class="per">/mo</span>
            </div>
            <p class="plan-card-desc">{{ p.description }}</p>
            <ul class="plan-limits">
              <li v-for="m in METRICS" :key="m.key">
                <span class="tick">✓</span>
                {{ p.limits[m.key] === null ? 'Unlimited' : formatNumber(p.limits[m.key] as number) }}
                {{ m.label.toLowerCase() }}
              </li>
            </ul>
            <!-- Deliberately not a working upgrade button. Checkout does not
                 exist yet, and a button that silently does nothing is worse
                 than an honest note. -->
            <p class="plan-card-cta">
              <span v-if="p.code === currentPlan?.code" class="muted-note">You're on this plan</span>
              <span v-else class="muted-note">Contact us to switch</span>
            </p>
          </article>
        </div>
      </section>
    </template>
  </div>
</template>

<style scoped>
.usage-page {
  display: flex;
  flex-direction: column;
  gap: var(--space-lg);
  max-width: 1000px;
}

.page-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-md);
  flex-wrap: wrap;
}

.page-head h1 {
  font-family: var(--font-display);
  font-size: var(--text-2xl);
  color: var(--text);
  margin: 0 0 var(--space-xs);
}

.page-sub {
  color: var(--muted);
  font-size: var(--text-sm);
  margin: 0;
}

.alert-error {
  color: var(--error-color);
  background: var(--error-bg);
  border: 1px solid color-mix(in srgb, var(--error-color) 25%, transparent);
  border-radius: var(--radius-md);
  padding: var(--space-md);
  font-size: var(--text-sm);
}

/* Loading */
.skeleton-grid {
  display: flex;
  flex-direction: column;
  gap: var(--space-md);
}

.skeleton-row {
  height: 62px;
  border-radius: var(--radius-md);
  background: linear-gradient(90deg, var(--o05), var(--o10), var(--o05));
  background-size: 200% 100%;
  animation: usage-shimmer 1.4s ease-in-out infinite;
}

@keyframes usage-shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}

@media (prefers-reduced-motion: reduce) {
  .skeleton-row { animation: none; }
}

.section-heading {
  font-family: var(--font-display);
  font-size: var(--text-lg);
  color: var(--text);
  margin: 0 0 var(--space-lg);
}

/* Current plan banner */
.plan-summary {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-lg);
  flex-wrap: wrap;
  background: linear-gradient(135deg, var(--accent-bg-08), var(--surface) 60%);
  border-color: var(--accent-border);
}

.plan-eyebrow {
  display: block;
  font-size: var(--text-xs);
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--muted2);
  margin-bottom: var(--space-xs);
}

.plan-id h2 {
  font-family: var(--font-display);
  font-size: var(--text-xl);
  color: var(--text);
  margin: 0 0 var(--space-xs);
}

.plan-id p {
  color: var(--muted);
  font-size: var(--text-sm);
  margin: 0;
}

.plan-price {
  text-align: right;
}

.plan-price .amount {
  font-family: var(--font-display);
  font-size: var(--text-2xl);
  font-weight: 700;
  color: var(--accent-ink);
}

.plan-price .per {
  display: block;
  font-size: var(--text-xs);
  color: var(--muted2);
}

/* Meters */
.meters {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-lg);
}

.meter-head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: var(--space-md);
  margin-bottom: var(--space-sm);
}

.meter-label .name {
  display: block;
  font-size: var(--text-sm);
  font-weight: 600;
  color: var(--text2);
}

.meter-label .hint {
  display: block;
  font-size: var(--text-xs);
  color: var(--muted2);
  margin-top: 2px;
}

.meter-value {
  text-align: right;
  white-space: nowrap;
  /* Counts line up down the column as they change width */
  font-variant-numeric: tabular-nums;
}

.meter-value strong {
  font-size: var(--text-lg);
  color: var(--text);
}

.meter-value.warn strong { color: var(--warning-color); }
.meter-value.critical strong,
.meter-value.over strong { color: var(--error-color); }

.meter-value .limit {
  font-size: var(--text-xs);
  color: var(--muted2);
  margin-left: var(--space-xs);
}

.track {
  height: 6px;
  background: var(--o08);
  border-radius: var(--radius-full);
  overflow: hidden;
}

.fill {
  height: 100%;
  border-radius: var(--radius-full);
  background: var(--accent-solid);
  transition: width var(--transition-normal);
}

.fill.warn { background: var(--warning-color); }
.fill.critical,
.fill.over { background: var(--error-color); }

.meter-note {
  font-size: var(--text-xs);
  margin: var(--space-sm) 0 0;
}

.meter-note.over { color: var(--error-color); }

/* Plan catalog */
.plan-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
  gap: var(--space-md);
}

.plan-card {
  border: 1px solid var(--o08);
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
  background: var(--bg2);
  display: flex;
  flex-direction: column;
  gap: var(--space-sm);
}

.plan-card.current {
  border-color: var(--accent-border);
  background: var(--accent-bg-06);
}

.plan-card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-sm);
}

.plan-card-head h3 {
  font-family: var(--font-display);
  font-size: var(--text-base);
  color: var(--text);
  margin: 0;
}

.chip {
  font-size: var(--text-xs);
  padding: 2px 8px;
  border-radius: var(--radius-pill);
  background: var(--accent-solid);
  color: #0B0C10;
  font-weight: 600;
}

.plan-card-price .amount {
  font-family: var(--font-display);
  font-size: var(--text-xl);
  font-weight: 700;
  color: var(--text);
}

.plan-card-price .per {
  font-size: var(--text-xs);
  color: var(--muted2);
}

.plan-card-desc {
  font-size: var(--text-xs);
  color: var(--muted);
  margin: 0;
  min-height: 2.4em;
}

.plan-limits {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-xs);
  font-size: var(--text-xs);
  color: var(--text3);
}

.plan-limits .tick {
  color: var(--accent-ink);
  font-weight: 700;
  margin-right: 4px;
}

.plan-card-cta {
  margin: var(--space-sm) 0 0;
}

.muted-note {
  font-size: var(--text-xs);
  color: var(--muted2);
}

@media (max-width: 640px) {
  .plan-summary { flex-direction: column; align-items: flex-start; }
  .plan-price { text-align: left; }
}
</style>
