<!--
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { RcaDocument } from '@/types/ticket'

const props = withDefaults(
  defineProps<{
    rca: RcaDocument
    canManage: boolean
    canNotify: boolean
    /** A save/send is in flight — both actions lock so nothing sends twice. */
    isBusy?: boolean
  }>(),
  { isBusy: false },
)

const emit = defineEmits<{
  (e: 'save-draft', customerSummary: string): void
  (e: 'send-customer', customerSummary: string): void
}>()

const customerDraft = ref(props.rca.customer_summary || '')
watch(
  () => props.rca.customer_summary,
  (next) => {
    customerDraft.value = next || ''
  },
)

interface Section {
  id: string
  label: string
  present: boolean
}

const sections = computed<Section[]>(() => [
  { id: 'rca-summary', label: 'Summary', present: !!props.rca.summary },
  { id: 'rca-impact', label: 'Impact', present: !!props.rca.impact },
  { id: 'rca-timeline', label: 'Timeline', present: !!props.rca.timeline?.length },
  { id: 'rca-log', label: 'Investigation log', present: !!props.rca.investigation_log },
  { id: 'rca-factors', label: 'Contributing factors', present: !!props.rca.contributing_factors?.length },
  { id: 'rca-conclusion', label: 'Conclusion', present: !!props.rca.conclusion },
  { id: 'rca-remediation', label: 'Remediation', present: !!props.rca.remediation },
  { id: 'rca-prevention', label: 'Prevention', present: !!props.rca.prevention },
  { id: 'rca-customer', label: 'Customer summary', present: true },
])

function jumpTo(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
</script>

<template>
  <div class="rca-doc">
    <div class="rca-head">
      <div>
        <div class="rca-title">Root-cause analysis</div>
        <div class="rca-byline">
          Generated by Growmiq mini AI
          <template v-if="rca.reviewed_by_name"> · reviewed by {{ rca.reviewed_by_name }}</template>
          <template v-else> · not yet reviewed</template>
          <span class="version mono">v{{ rca.version }}</span>
          <span v-if="rca.is_partial" class="partial-tag">Partial — budget reached</span>
        </div>
      </div>
      <div v-if="rca.confidence != null" class="rca-confidence mono">
        confidence {{ rca.confidence.toFixed(2) }}
      </div>
    </div>

    <div class="rca-grid">
      <nav class="rca-toc">
        <button
          v-for="section in sections.filter((s) => s.present)"
          :key="section.id"
          class="toc-link"
          @click="jumpTo(section.id)"
        >
          {{ section.label }}
        </button>
      </nav>

      <div class="rca-body">
        <section v-if="rca.summary" id="rca-summary">
          <h4 class="section-label">Summary</h4>
          <p class="section-text">{{ rca.summary }}</p>
        </section>

        <section v-if="rca.impact" id="rca-impact">
          <h4 class="section-label">Impact</h4>
          <p class="section-text">{{ rca.impact }}</p>
        </section>

        <section v-if="rca.timeline?.length" id="rca-timeline">
          <h4 class="section-label">Timeline</h4>
          <div class="timeline">
            <div v-for="(entry, i) in rca.timeline" :key="i" class="timeline-row">
              <span class="timeline-time mono">{{ entry.time }}</span>
              <span class="timeline-event">{{ entry.event }}</span>
            </div>
          </div>
        </section>

        <section v-if="rca.investigation_log" id="rca-log">
          <h4 class="section-label">Investigation log</h4>
          <p class="section-text">{{ rca.investigation_log }}</p>
        </section>

        <section v-if="rca.contributing_factors?.length" id="rca-factors">
          <h4 class="section-label">Contributing factors</h4>
          <ul class="factor-list">
            <li v-for="(factor, i) in rca.contributing_factors" :key="i">{{ factor }}</li>
          </ul>
        </section>

        <section v-if="rca.conclusion" id="rca-conclusion">
          <h4 class="section-label">Conclusion</h4>
          <p class="section-text conclusion">{{ rca.conclusion }}</p>
        </section>

        <section v-if="rca.remediation" id="rca-remediation">
          <h4 class="section-label">Remediation</h4>
          <p class="section-text">{{ rca.remediation }}</p>
        </section>

        <section v-if="rca.prevention" id="rca-prevention">
          <h4 class="section-label">Prevention</h4>
          <p class="section-text">{{ rca.prevention }}</p>
        </section>

        <section id="rca-customer">
          <h4 class="section-label">Customer summary</h4>
          <div class="customer-card">
            <textarea
              v-if="canManage"
              v-model="customerDraft"
              class="customer-editor"
              placeholder="Plain-language summary for the customer…"
            ></textarea>
            <p v-else class="section-text">{{ rca.customer_summary || '—' }}</p>
            <div v-if="canManage" class="customer-actions">
              <span v-if="!canNotify" class="no-channel-note">
                No customer channel — link a conversation or add a customer email to send.
              </span>
              <button
                class="draft-btn"
                :disabled="props.isBusy"
                @click="emit('save-draft', customerDraft)"
              >
                Save draft
              </button>
              <button
                class="send-btn"
                :disabled="props.isBusy || !canNotify || !customerDraft.trim()"
                @click="emit('send-customer', customerDraft)"
              >
                {{ props.isBusy ? 'Sending…' : 'Send to customer' }}
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

<style scoped>
.rca-doc {
  background: var(--surface);
  border: 1px solid var(--o08);
  border-radius: 15px;
  padding: 18px 20px;
}
.rca-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 15px;
}
.rca-title {
  font-family: var(--font-display);
  font-weight: var(--font-weight-bold);
  font-size: 15px;
  color: var(--text);
}
.rca-byline {
  margin-top: 3px;
  font-size: 11.5px;
  color: var(--faint);
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}
.version {
  color: var(--muted2);
  background: var(--o05);
  border: 1px solid var(--o08);
  padding: 1px 6px;
  border-radius: 5px;
  font-size: 10px;
}
.partial-tag {
  font-family: var(--font-mono);
  font-size: 9.5px;
  color: var(--c-warn);
  background: color-mix(in srgb, var(--c-warn) 12%, transparent);
  padding: 2px 7px;
  border-radius: 6px;
}
.rca-confidence {
  font-size: 11px;
  color: var(--muted2);
  flex-shrink: 0;
}
.mono {
  font-family: var(--font-mono);
}
.rca-grid {
  display: grid;
  grid-template-columns: 148px minmax(0, 1fr);
  gap: 18px;
  align-items: start;
}
.rca-toc {
  position: sticky;
  top: 16px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.toc-link {
  text-align: left;
  padding: 5px 9px;
  background: transparent;
  border: none;
  border-radius: 7px;
  color: var(--muted);
  font-size: 11.5px;
  cursor: pointer;
}
.toc-link:hover {
  background: var(--o05);
  color: var(--text);
}
.rca-body {
  display: flex;
  flex-direction: column;
  gap: 17px;
  min-width: 0;
}
.section-label {
  font-family: var(--font-mono);
  font-size: 10px;
  letter-spacing: 0.09em;
  text-transform: uppercase;
  color: var(--faint);
  margin: 0 0 7px;
}
.section-text {
  margin: 0;
  font-size: 13px;
  line-height: 1.6;
  color: var(--text3);
  white-space: pre-wrap;
  word-break: break-word;
}
.section-text.conclusion {
  color: var(--text);
}
.timeline {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.timeline-row {
  display: flex;
  gap: 12px;
  font-size: 12.5px;
}
.timeline-time {
  color: var(--muted2);
  font-size: 11px;
  flex-shrink: 0;
  min-width: 92px;
  padding-top: 1px;
}
.timeline-event {
  color: var(--text3);
  line-height: 1.5;
}
.factor-list {
  margin: 0;
  padding-left: 18px;
  font-size: 13px;
  line-height: 1.7;
  color: var(--text3);
}
.customer-card {
  border: 1.5px solid var(--c-teal);
  background: var(--teal-bg-10, color-mix(in srgb, var(--c-teal) 8%, transparent));
  border-radius: 12px;
  padding: 13px 14px;
}
.customer-editor {
  width: 100%;
  min-height: 88px;
  resize: vertical;
  background: var(--surface);
  border: 1px solid var(--o08);
  border-radius: 9px;
  padding: 10px 12px;
  color: var(--text);
  font-size: 13px;
  line-height: 1.55;
  outline: none;
}
.customer-actions {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 9px;
  margin-top: 10px;
  flex-wrap: wrap;
}
.no-channel-note {
  margin-right: auto;
  font-size: 11px;
  color: var(--faint);
}
.draft-btn {
  padding: 7px 13px;
  background: var(--o05);
  border: 1px solid var(--o10);
  color: var(--text);
  border-radius: 9px;
  font-size: 12px;
  cursor: pointer;
}
.send-btn {
  padding: 7px 15px;
  background: var(--c-teal);
  color: var(--on-light, #04140d);
  border: none;
  border-radius: 9px;
  font-size: 12px;
  font-weight: var(--font-weight-bold);
  cursor: pointer;
}
.send-btn:disabled,
.draft-btn:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}
@media (max-width: 900px) {
  .rca-grid {
    grid-template-columns: 1fr;
  }
  .rca-toc {
    position: static;
    flex-direction: row;
    flex-wrap: wrap;
  }
}
</style>
