"""make user deletion possible: add ondelete to every FK pointing at users.id

Revision ID: add_user_delete_cascades_001
Revises: add_plan_features_001
Create Date: 2026-08-14

Six foreign keys referenced users.id with no ON DELETE action, so Postgres
defaulted to NO ACTION and refused any delete that had a dependent row. The
console's "remove user" would therefore have failed with an IntegrityError —
a 500 with a constraint name in it — for essentially every real account, since
`notifications.user_id` is NOT NULL and every active user has notifications.

Direction per table is chosen by what the row means without its user:

  * notifications      CASCADE  — a notification addressed to a deleted account
                                  is unreachable and unactionable.
  * everything else    SET NULL — the row is the tenant's work or their record,
                                  and must outlive the staff member who made it.

Two of those columns were NOT NULL and are widened to nullable, because SET
NULL on a NOT NULL column is a constraint that can only ever fail.
"""
from alembic import op
import sqlalchemy as sa

revision = 'add_user_delete_cascades_001'
down_revision = 'add_plan_features_001'
branch_labels = None
depends_on = None


# (table, column, ondelete, was_not_null)
FKS = [
    ('notifications', 'user_id', 'CASCADE', False),
    ('widget_apps', 'created_by', 'SET NULL', True),
    ('workflows', 'created_by', 'SET NULL', False),
    ('knowledge_queue', 'user_id', 'SET NULL', False),
    ('crm_connections', 'connected_by_user_id', 'SET NULL', False),
    ('lead_capture_configs', 'assignment_target_user_id', 'SET NULL', False),
    # Association row, not a record: it has no meaning without both ends.
    ('user_groups', 'user_id', 'CASCADE', False),
]


def _constraint_name(conn, table: str, column: str) -> str | None:
    """Find the existing FK by what it points at rather than by name.

    Constraint names are generated by whichever migration created the table and
    differ between deployments that have been through different histories.
    Dropping by a guessed name would work here and fail on somebody else's
    database.
    """
    return conn.execute(sa.text("""
        SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name
         AND tc.table_schema = ccu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_name = :table
          AND kcu.column_name = :column
          AND ccu.table_name = 'users'
        LIMIT 1
    """), {"table": table, "column": column}).scalar()


def upgrade() -> None:
    conn = op.get_bind()

    for table, column, ondelete, was_not_null in FKS:
        # Skip tables this deployment does not have. The enterprise submodule
        # and several optional integrations create their own, and a migration
        # that assumes all of them exist cannot run on a smaller install.
        exists = conn.execute(sa.text(
            "SELECT to_regclass(:t)"
        ), {"t": f"public.{table}"}).scalar()
        if not exists:
            continue

        name = _constraint_name(conn, table, column)
        if name:
            op.drop_constraint(name, table, type_='foreignkey')

        if was_not_null:
            # SET NULL against a NOT NULL column is a constraint that can only
            # fail, so widen first.
            op.alter_column(table, column, existing_type=sa.dialects.postgresql.UUID(),
                            nullable=True)

        op.create_foreign_key(
            f'fk_{table}_{column}_users', table, 'users',
            [column], ['id'], ondelete=ondelete,
        )


def downgrade() -> None:
    conn = op.get_bind()
    for table, column, _ondelete, was_not_null in FKS:
        exists = conn.execute(sa.text(
            "SELECT to_regclass(:t)"
        ), {"t": f"public.{table}"}).scalar()
        if not exists:
            continue

        op.drop_constraint(f'fk_{table}_{column}_users', table, type_='foreignkey')
        op.create_foreign_key(None, table, 'users', [column], ['id'])
        if was_not_null:
            # Only safe if no row acquired a NULL while the constraint was
            # relaxed; a deployment that deleted a user in between will need
            # those rows reassigned by hand first.
            op.alter_column(table, column, existing_type=sa.dialects.postgresql.UUID(),
                            nullable=False)
